KanbanBoard/KanbanBoard/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KanbanBoard.Data;
using KanbanBoard.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace KanbanBoard.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<KanbanBoardUser> _userManager;

        public ProjectsController(ApplicationDbContext context, UserManager<KanbanBoardUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);

            var projects = _context.Projects
                .Include(p => p.KanbanBoardUser)
                .Where(p => p.ProjectOwnerId == userId); // check ownership
            return View(await projects.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            /*var project = await _context.Projects
                .Include(p => p.KanbanBoardUser)
                .FirstOrDefaultAsync(m => m.ProjectId == id);*/
            var project = await GetUserProjectAndCheckIfUserIsAuthorisedToAccessProjectAsync(id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            ViewData["ProjectOwnerId"] = new SelectList(_context.Users, "Id", "Id");
            DateTime currentDateAndTime = DateTime.Now;
            var userId = _userManager.GetUserId(User);
            var project = new Project
            {
                ProjectCreationDate = DateOnly.FromDateTime(currentDateAndTime),
                ProjectOwnerId = userId, 
            };
            return View(project);
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProjectId,ProjectName,ProjectDescription,ProjectCreationDate,ProjectOwnerId")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectOwnerId"] = new SelectList(_context.Users, "Id", "Id", project.ProjectOwnerId);
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var project = await _context.Projects.FindAsync(id);
            var project = await GetUserProjectAndCheckIfUserIsAuthorisedToAccessProjectAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["ProjectOwnerId"] = new SelectList(_context.Users, "Id", "Id", project.ProjectOwnerId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectId,ProjectName,ProjectDescription,ProjectCreationDate,ProjectOwnerId")] Project project)
        {
            if (id != project.ProjectId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ProjectId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectOwnerId"] = new SelectList(_context.Users, "Id", "Id", project.ProjectOwnerId);
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var project = await GetUserProjectAndCheckIfUserIsAuthorisedToAccessProjectAsync(id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await GetUserProjectAndCheckIfUserIsAuthorisedToAccessProjectAsync(id);
            if (project != null)
            {
                _context.Projects.Remove(project);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Projects.Any(e => e.ProjectId == id);
        }

        private async Task<Project?> GetUserProjectAndCheckIfUserIsAuthorisedToAccessProjectAsync(int? id)
        {
            var userId = _userManager.GetUserId(User);
            return await _context.Projects.FirstOrDefaultAsync(p => (p.ProjectId == id) && (p.ProjectOwnerId == userId));
        }
    }
}

KanbanBoard/KanbanBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KanbanBoard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KanbanBoard.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KanbanBoard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name = "_MyProjectsPartial"/>
                        <partial name = "_ManageUsersPartial"/>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - KanbanBoard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

KanbanBoard/KanbanBoard/Views/Shared/_ManageUsersPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<KanbanBoardUser> SignInManager
@inject UserManager<KanbanBoardUser> UserManager

@if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Manage Users</a>
    </li>
}

KanbanBoard/KanbanBoard/Views/Shared/_MyProjectsPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<KanbanBoardUser> SignInManager
@inject UserManager<KanbanBoardUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">My Projects</a>
    </li>
}