KanbanBoard/KanbanBoard/Models/Project.cs
using Humanizer;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KanbanBoard.Models
{
    public class Project
    {
        [Key]
        [Display (Name = "ID")]
        public int ProjectId { get; set; }
        [Display(Name = "Name")]
        public string? ProjectName { get; set; }
        [Display(Name = "Description")]
        public string? ProjectDescription { get; set; }
        [Display(Name = "Creation Date")]
        public DateOnly ProjectCreationDate { get; set; }

        
        [ForeignKey("KanbanBoardUser")]
        public required string ProjectOwnerId { get; set; }

        public KanbanBoardUser? KanbanBoardUser { get; set; } // this is nullable because i need to be able to create a Project object without this Field and send it to the view. 
        

        public ICollection<KanbanBoardTask> KanbanBoardTasks { get; set; } = new List<KanbanBoardTask>();

    }
}

KanbanBoard/KanbanBoard/Controllers/KanbanBoardTasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KanbanBoard.Data;
using KanbanBoard.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace KanbanBoard.Controllers
{
    [Authorize]
    public class KanbanBoardTasksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<KanbanBoardUser> _userManager;

        public KanbanBoardTasksController(ApplicationDbContext context, UserManager<KanbanBoardUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: KanbanBoardTasks
        public async Task<IActionResult> Index(int ProjectId)
        {
            var applicationDbContext = _context.KanbanBoardTasks
                .Include(t => t.KanbanBoardUser)
                .Where(t => t.ProjectID == ProjectId);
            ViewData["ProjectID"] = ProjectId; // This is needed because the tasks index page allows a user to create a new task which needs a ProjectId foreign key
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: KanbanBoardTasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kanbanBoardTask = await _context.KanbanBoardTasks
                .Include(k => k.KanbanBoardUser)
                .FirstOrDefaultAsync(m => m.TaskId == id);
            if (kanbanBoardTask == null)
            {
                return NotFound();
            }

            return View(kanbanBoardTask);
        }

        // GET: KanbanBoardTasks/Create
        public IActionResult Create(int ProjectId)
        {
            ViewData["TaskAssignedUserId"] = new SelectList(_context.Users, "Id", "Id");
            var userId = _userManager.GetUserId(User);
            var kanbanBoardTask = new KanbanBoardTask
            {
                TaskAssignedUserId = userId,
                ProjectID = ProjectId
            };
            return View(kanbanBoardTask);
        }

        // POST: KanbanBoardTasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TaskId,TaskName,TaskDescription,TaskAssignedUserId,ProjectID")] KanbanBoardTask kanbanBoardTask)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kanbanBoardTask);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { ProjectId = kanbanBoardTask.ProjectID });
            }
            ViewData["TaskAssignedUserId"] = new SelectList(_context.Users, "Id", "Id", kanbanBoardTask.TaskAssignedUserId);
            return View(kanbanBoardTask);
        }

        // GET: KanbanBoardTasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kanbanBoardTask = await _context.KanbanBoardTasks.FindAsync(id);
            if (kanbanBoardTask == null)
            {
                return NotFound();
            }
            ViewData["TaskAssignedUserId"] = new SelectList(_context.Users, "Id", "Id", kanbanBoardTask.TaskAssignedUserId);
            return View(kanbanBoardTask);
        }

        // POST: KanbanBoardTasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TaskId,TaskName,TaskDescription,TaskStatus,ProjectID,TaskAssignedUserId")] KanbanBoardTask kanbanBoardTask)
        {
            if (id != kanbanBoardTask.TaskId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kanbanBoardTask);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KanbanBoardTaskExists(kanbanBoardTask.TaskId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { ProjectId = kanbanBoardTask.ProjectID });
            }
            ViewData["TaskAssignedUserId"] = new SelectList(_context.Users, "Id", "Id", kanbanBoardTask.TaskAssignedUserId);
            return View(kanbanBoardTask);
        }

        // GET: KanbanBoardTasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kanbanBoardTask = await _context.KanbanBoardTasks
                .Include(k => k.KanbanBoardUser)
                .FirstOrDefaultAsync(m => m.TaskId == id);
            if (kanbanBoardTask == null)
            {
                return NotFound();
            }

            return View(kanbanBoardTask);
        }

        // POST: KanbanBoardTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kanbanBoardTask = await _context.KanbanBoardTasks.FindAsync(id);
            if (kanbanBoardTask != null)
            {
                _context.KanbanBoardTasks.Remove(kanbanBoardTask);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KanbanBoardTaskExists(int id)
        {
            return _context.KanbanBoardTasks.Any(e => e.TaskId == id);
        }
    }
}

KanbanBoard/KanbanBoard/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KanbanBoard.Data;
using KanbanBoard.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace KanbanBoard.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<KanbanBoardUser> _userManager;

        public ProjectsController(ApplicationDbContext context, UserManager<KanbanBoardUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);

            var projects = _context.Projects
                .Include(p => p.KanbanBoardUser)
                .Where(p => p.ProjectOwnerId == userId); // check ownership
            return View(await projects.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            /*var project = await _context.Projects
                .Include(p => p.KanbanBoardUser)
                .FirstOrDefaultAsync(m => m.ProjectId == id);*/
            var project = await GetUserProjectAndCheckIfUserIsAuthorisedToAccessProjectAsync(id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            ViewData["ProjectOwnerId"] = new SelectList(_context.Users, "Id", "Id");
            DateTime currentDateAndTime = DateTime.Now;
            var userId = _userManager.GetUserId(User);
            var project = new Project
            {
                ProjectCreationDate = DateOnly.FromDateTime(currentDateAndTime),
                ProjectOwnerId = userId, 
            };
            return View(project);
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProjectId,ProjectName,ProjectDescription,ProjectCreationDate,ProjectOwnerId")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectOwnerId"] = new SelectList(_context.Users, "Id", "Id", project.ProjectOwnerId);
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var project = await _context.Projects.FindAsync(id);
            var project = await GetUserProjectAndCheckIfUserIsAuthorisedToAccessProjectAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["ProjectOwnerId"] = new SelectList(_context.Users, "Id", "Id", project.ProjectOwnerId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectId,ProjectName,ProjectDescription,ProjectCreationDate,ProjectOwnerId")] Project project)
        {
            if (id != project.ProjectId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ProjectId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectOwnerId"] = new SelectList(_context.Users, "Id", "Id", project.ProjectOwnerId);
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var project = await GetUserProjectAndCheckIfUserIsAuthorisedToAccessProjectAsync(id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await GetUserProjectAndCheckIfUserIsAuthorisedToAccessProjectAsync(id);
            if (project != null)
            {
                _context.Projects.Remove(project);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Projects.Any(e => e.ProjectId == id);
        }

        private async Task<Project?> GetUserProjectAndCheckIfUserIsAuthorisedToAccessProjectAsync(int? id)
        {
            var userId = _userManager.GetUserId(User);
            return await _context.Projects.FirstOrDefaultAsync(p => (p.ProjectId == id) && (p.ProjectOwnerId == userId));
        }
    }
}

KanbanBoard/KanbanBoard/Views/Projects/Create.cshtml
@model KanbanBoard.Models.Project

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectDescription" class="control-label"></label>
                <input asp-for="ProjectDescription" class="form-control" />
                <span asp-validation-for="ProjectDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectCreationDate" class="control-label"></label>
                <input asp-for="ProjectCreationDate" class="form-control" readonly />
                <span asp-validation-for="ProjectCreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="ProjectOwnerId" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KanbanBoard/KanbanBoard/Views/Projects/Delete.cshtml
@model KanbanBoard.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectCreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectCreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KanbanBoardUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KanbanBoardUser.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProjectId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KanbanBoard/KanbanBoard/Views/Projects/Details.cshtml
@model KanbanBoard.Models.Project

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectCreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectCreationDate)
        </dd>
        @*
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KanbanBoardUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KanbanBoardUser.Id)
        </dd>
        *@
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ProjectId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

KanbanBoard/KanbanBoard/Views/Projects/Edit.cshtml
@model KanbanBoard.Models.Project

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProjectId" />
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectDescription" class="control-label"></label>
                <input asp-for="ProjectDescription" class="form-control" />
                <span asp-validation-for="ProjectDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectCreationDate" class="control-label"></label>
                <input asp-for="ProjectCreationDate" class="form-control" />
                <span asp-validation-for="ProjectCreationDate" class="text-danger"></span>
            </div>
            <!--
            <div class="form-group">
                <label asp-for="ProjectOwnerId" class="control-label"></label>
                <select asp-for="ProjectOwnerId" class="form-control" asp-items="ViewBag.ProjectOwnerId"></select>
                <span asp-validation-for="ProjectOwnerId" class="text-danger"></span>
            </div>
            -->
            <input type="hidden" asp-for="ProjectOwnerId" />
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-ProjectOwnerId="@Model.ProjectOwnerId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KanbanBoard/KanbanBoard/Views/Projects/Index.cshtml
@model IEnumerable<KanbanBoard.Models.Project>

@{
    ViewData["Title"] = "My Projects";
}

<h1>My Projects</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProjectName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectCreationDate)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectCreationDate)
            </td>
            <td>
                <a asp-controller="KanbanBoardTasks" asp-action="Index" asp-route-ProjectId="@item.ProjectId">Board</a> |
                <a asp-action="Edit" asp-route-id="@item.ProjectId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProjectId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProjectId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>